version: "3.3"

services:

  portainer:
    image: portainer/portainer
    ports:
        - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    command: ["-H unix:///var/run/docker.sock"]
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  gitlabPostgresql_data:
  gitlab_data:
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2 # https://docs.docker.com/docker-for-aws/persistent-data-volumes/#use-a-unique-volume-per-task-using-ebs && http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
      size: 25
      iops: 1000
      backing: relocatable
  jenkins_home:
  nexus_data:
  postgresql:
  postgresql_data:
  redis_data:
  sonarqube_bundled_plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
