version: "3.3"

services:

    metricbeat:
        image: quay.io/shazchaudhry/docker-metricbeat:${ELASTIC_VERSION:-5.5.1}
        volumes:
          - metricbea_data:/usr/share/metricbeat/data
          - /proc:/hostfs/proc:ro
          - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
          - /:/hostfs:ro
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - HOST=elasticsearch
          - PORT=9200
          - PROTOCOL=http
          - USERNAME=elastic
          - PASSWORD=changeme
        deploy:
            mode: global
        command: metricbeat -e  -system.hostfs=/hostfs

volumes:
  metricbea_data:
