version: "3.3"

services:

  portainer:
    image: portainer/portainer # https://portainer.readthedocs.io/en/stable/deployment.html
    ports:
        - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-H", "unix:///var/run/docker.sock"]
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  gitlabPostgresql_data:
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2 # https://docs.docker.com/docker-for-aws/persistent-data-volumes/#use-a-unique-volume-per-task-using-ebs && http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
      size: 25
      iops: 1000
      backing: relocatable
  gitlab_data:
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2
      size: 25
      iops: 1000
      backing: relocatable
  jenkins_home:
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2
      size: 25
      iops: 1000
      backing: relocatable
  nexus_data:
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2
      size: 25
      iops: 1000
      backing: relocatable
