version: "3"
 
services:
    
    jenkins:
        image: stefanprodan/jenkins
        environment:
            - JENKINS_OPTS='--prefix=/jenkins'
        networks:
            - prodnet
            - proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - java_home:/var/jenkins_home
            - ansible_home:/etc/ansible
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.servicePath=/jenkins
                - com.df.port=8080
    
    nexus:
        image: sonatype/nexus3
        environment:
            - NEXUS_CONTEXT=nexus
        networks:
            - prodnet
            - proxy
        volumes:
            - nexus_data:/nexus-data
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.servicePath=/nexus
                - com.df.port=8081
                
    sonarqube:
        image: sonarqube
        environment:
            - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
        networks:
            - sonarqube
            - prodnet
            - proxy
        volumes:            
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins        
        command: ["-Dsonar.web.context=/sonar"]
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.servicePath=/sonar
                - com.df.port=9000

    sonardb:
        image: postgres
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        networks:
            - sonarqube
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
 
networks:
    proxy:
        external: true
    prodnet:
        external: true
    sonarqube:
        external: true
    gitlab:
        external: true
 
volumes:
    nexus_data:
    java_home:
    ansible_home:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins:
    postgresql:
    postgresql_data: